spec:
  replicas: 1
  imagePullSecrets: ""

environment: ""

config:
  otel:
    exporterOtlpEndpoint: ""
  connectionStrings:
    postgres: ""
  jwt:
    audience: ""
    authority: ""
  cmsServices:
    showManagement:
      baseAddress:
    imageAssetManagement:
      baseAddress: