spec:
  replicas: 1
  imagePullSecrets: ""

config:
  connectionStrings:
    postgres: ""
  jwt:
    audience: ""
    authority: ""
  cmsServices:
    showManagement:
      baseAddress:
    imageAssetManagement:
      baseAddress: